// <auto-generated />
using System;
using AstroView.WebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AstroView.WebApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251022093008_CaesarDatasetCreatedAt")]
    partial class CaesarDatasetCreatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.CaesarJobDbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CaesarJobId")
                        .HasColumnType("longtext");

                    b.Property<string>("CaesarJobState")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CaesarJobStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayModeId")
                        .HasColumnType("int");

                    b.Property<string>("Error")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FinishedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResultJobId")
                        .HasColumnType("longtext");

                    b.Property<int>("ResultJobStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AppName");

                    b.HasIndex("DatasetId");

                    b.HasIndex("DisplayModeId");

                    b.HasIndex("StartedDate");

                    b.HasIndex("UserId");

                    b.ToTable("CaesarJobs");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.ChangeDbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.HasIndex("Date");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("Changes");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.ClusterDbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaesarJobId")
                        .HasColumnType("int");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CaesarJobId");

                    b.HasIndex("Index");

                    b.ToTable("Clusters");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.ClusterItemDbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClusterId")
                        .HasColumnType("int");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<double>("OutlierScore")
                        .HasColumnType("double");

                    b.Property<double>("Probability")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.HasIndex("ImageId");

                    b.ToTable("ClusterItems");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.DatasetDbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ShareType")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("UserId");

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.DatasetJobDbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("JobStatus")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.HasIndex("Date");

                    b.HasIndex("JobId");

                    b.HasIndex("JobStatus");

                    b.HasIndex("UserId");

                    b.ToTable("DatasetJobs");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.DatasetOptionDbe", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UserId", "DatasetId");

                    b.HasIndex("DatasetId");

                    b.HasIndex("IsFavorite");

                    b.ToTable("DatasetOptions");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.DisplayModeDbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CaesarDatasetCreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CaesarDatasetJobId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CaesarDatasetJobStatus")
                        .HasColumnType("int");

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImagesPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ParamsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PixPlotJobId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PixPlotJobStatus")
                        .HasColumnType("int");

                    b.Property<string>("PixPlotParamsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RenderJobId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RenderJobStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId", "IsDefault");

                    b.HasIndex("DatasetId", "Name")
                        .IsUnique();

                    b.ToTable("DisplayModes");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.ExportDbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("JobId")
                        .HasColumnType("longtext");

                    b.Property<int>("JobStatus")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.HasIndex("Date");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("Exports");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.ImageDbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("B")
                        .HasColumnType("double");

                    b.Property<double?>("Bkg")
                        .HasColumnType("double");

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<double?>("Dec")
                        .HasColumnType("double");

                    b.Property<double?>("Dx")
                        .HasColumnType("double");

                    b.Property<double?>("Dy")
                        .HasColumnType("double");

                    b.Property<string>("Features")
                        .HasColumnType("longtext");

                    b.Property<bool>("HasFeatures")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("L")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Nsources")
                        .HasColumnType("int");

                    b.Property<int?>("Nx")
                        .HasColumnType("int");

                    b.Property<int?>("Ny")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Project")
                        .HasColumnType("varchar(255)");

                    b.Property<double?>("Ra")
                        .HasColumnType("double");

                    b.Property<double?>("Rms")
                        .HasColumnType("double");

                    b.Property<string>("Survey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Telescope")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("B");

                    b.HasIndex("Dec");

                    b.HasIndex("L");

                    b.HasIndex("Project");

                    b.HasIndex("Ra");

                    b.HasIndex("Survey");

                    b.HasIndex("Telescope");

                    b.HasIndex("DatasetId", "HasFeatures");

                    b.HasIndex("DatasetId", "Name")
                        .IsUnique();

                    b.ToTable("Images");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.ImageLabelDbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<int>("LabelId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("LabelId");

                    b.HasIndex("ImageId", "LabelId")
                        .IsUnique();

                    b.ToTable("ImageLabels");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.IndividualSimilarDbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaesarJobId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CaesarJobId", "FilePath")
                        .IsUnique();

                    b.ToTable("IndividualSimilars");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.LabelDbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.OutlierDbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaesarJobId")
                        .HasColumnType("int");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOutlier")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("Score")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("CaesarJobId", "ImageId")
                        .IsUnique();

                    b.HasIndex("CaesarJobId", "IsOutlier");

                    b.HasIndex("CaesarJobId", "Score");

                    b.ToTable("Outliers");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.PredictionDbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaesarJobId")
                        .HasColumnType("int");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<int>("LabelId")
                        .HasColumnType("int");

                    b.Property<double>("Probability")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("LabelId");

                    b.HasIndex("CaesarJobId", "Probability");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.SimilarDbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaesarJobId")
                        .HasColumnType("int");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("CaesarJobId", "ImageId")
                        .IsUnique();

                    b.ToTable("Similars");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.UserDbe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LastDatasetId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NotedFiles")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LastDatasetId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.CaesarJobDbe", b =>
                {
                    b.HasOne("AstroView.WebApp.Data.Entities.DatasetDbe", "Dataset")
                        .WithMany("CaesarJobs")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AstroView.WebApp.Data.Entities.DisplayModeDbe", "DisplayMode")
                        .WithMany()
                        .HasForeignKey("DisplayModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AstroView.WebApp.Data.Entities.UserDbe", "User")
                        .WithMany("CaesarJobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");

                    b.Navigation("DisplayMode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.ChangeDbe", b =>
                {
                    b.HasOne("AstroView.WebApp.Data.Entities.DatasetDbe", "Dataset")
                        .WithMany("Changes")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AstroView.WebApp.Data.Entities.UserDbe", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.ClusterDbe", b =>
                {
                    b.HasOne("AstroView.WebApp.Data.Entities.CaesarJobDbe", "CaesarJob")
                        .WithMany()
                        .HasForeignKey("CaesarJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaesarJob");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.ClusterItemDbe", b =>
                {
                    b.HasOne("AstroView.WebApp.Data.Entities.ClusterDbe", "Cluster")
                        .WithMany("Items")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AstroView.WebApp.Data.Entities.ImageDbe", "Image")
                        .WithMany("ClusterItems")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.DatasetDbe", b =>
                {
                    b.HasOne("AstroView.WebApp.Data.Entities.UserDbe", "User")
                        .WithMany("Datasets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.DatasetJobDbe", b =>
                {
                    b.HasOne("AstroView.WebApp.Data.Entities.DatasetDbe", "Dataset")
                        .WithMany("Jobs")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AstroView.WebApp.Data.Entities.UserDbe", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.DatasetOptionDbe", b =>
                {
                    b.HasOne("AstroView.WebApp.Data.Entities.DatasetDbe", "Dataset")
                        .WithMany("Options")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AstroView.WebApp.Data.Entities.UserDbe", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.DisplayModeDbe", b =>
                {
                    b.HasOne("AstroView.WebApp.Data.Entities.DatasetDbe", "Dataset")
                        .WithMany("DisplayModes")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.ExportDbe", b =>
                {
                    b.HasOne("AstroView.WebApp.Data.Entities.DatasetDbe", "Dataset")
                        .WithMany("Exports")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AstroView.WebApp.Data.Entities.UserDbe", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.ImageDbe", b =>
                {
                    b.HasOne("AstroView.WebApp.Data.Entities.DatasetDbe", "Dataset")
                        .WithMany("Images")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.ImageLabelDbe", b =>
                {
                    b.HasOne("AstroView.WebApp.Data.Entities.ImageDbe", "Image")
                        .WithMany("Labels")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AstroView.WebApp.Data.Entities.LabelDbe", "Label")
                        .WithMany("ImageLabels")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Label");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.IndividualSimilarDbe", b =>
                {
                    b.HasOne("AstroView.WebApp.Data.Entities.CaesarJobDbe", "CaesarJob")
                        .WithMany()
                        .HasForeignKey("CaesarJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaesarJob");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.OutlierDbe", b =>
                {
                    b.HasOne("AstroView.WebApp.Data.Entities.CaesarJobDbe", "CaesarJob")
                        .WithMany()
                        .HasForeignKey("CaesarJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AstroView.WebApp.Data.Entities.ImageDbe", "Image")
                        .WithMany("Outliers")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaesarJob");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.PredictionDbe", b =>
                {
                    b.HasOne("AstroView.WebApp.Data.Entities.CaesarJobDbe", "CaesarJob")
                        .WithMany()
                        .HasForeignKey("CaesarJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AstroView.WebApp.Data.Entities.ImageDbe", "Image")
                        .WithMany("Predictions")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AstroView.WebApp.Data.Entities.LabelDbe", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaesarJob");

                    b.Navigation("Image");

                    b.Navigation("Label");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.SimilarDbe", b =>
                {
                    b.HasOne("AstroView.WebApp.Data.Entities.CaesarJobDbe", "CaesarJob")
                        .WithMany()
                        .HasForeignKey("CaesarJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AstroView.WebApp.Data.Entities.ImageDbe", "Image")
                        .WithMany("Similars")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaesarJob");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.UserDbe", b =>
                {
                    b.HasOne("AstroView.WebApp.Data.Entities.DatasetDbe", "Dataset")
                        .WithMany("Users")
                        .HasForeignKey("LastDatasetId");

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AstroView.WebApp.Data.Entities.UserDbe", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AstroView.WebApp.Data.Entities.UserDbe", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AstroView.WebApp.Data.Entities.UserDbe", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AstroView.WebApp.Data.Entities.UserDbe", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.ClusterDbe", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.DatasetDbe", b =>
                {
                    b.Navigation("CaesarJobs");

                    b.Navigation("Changes");

                    b.Navigation("DisplayModes");

                    b.Navigation("Exports");

                    b.Navigation("Images");

                    b.Navigation("Jobs");

                    b.Navigation("Options");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.ImageDbe", b =>
                {
                    b.Navigation("ClusterItems");

                    b.Navigation("Labels");

                    b.Navigation("Outliers");

                    b.Navigation("Predictions");

                    b.Navigation("Similars");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.LabelDbe", b =>
                {
                    b.Navigation("ImageLabels");
                });

            modelBuilder.Entity("AstroView.WebApp.Data.Entities.UserDbe", b =>
                {
                    b.Navigation("CaesarJobs");

                    b.Navigation("Datasets");
                });
#pragma warning restore 612, 618
        }
    }
}
